[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "viloedit"
version = "1.0.0"
description = "Code Editor Plugin for ViloxTerm"
authors = [{name = "ViloxTerm Team", email = "team@viloxterm.org"}]
readme = "README.md"
license = {text = "MIT"}
keywords = ["editor", "code", "syntax", "highlighting", "plugin"]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Text Editors",
]

dependencies = [
    "viloapp-sdk>=1.0.0",
    "PySide6>=6.5.0",
    "Pygments>=2.0.0",
    "tree-sitter>=0.20.0",
]

[project.optional-dependencies]
lsp = [
    "pylsp>=1.0.0",
    "python-lsp-jsonrpc>=1.0.0",
]
dev = [
    "pytest>=7.0",
    "pytest-qt>=4.2.0",
]

[project.entry-points."viloapp.plugins"]
editor = "viloedit.plugin:EditorPlugin"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
viloedit = [
    "themes/**/*",
    "languages/**/*",
]